Exercise 2
dmersiyanov/AndroidAcademy pull request #1
Opened 2018-09-30 12:53 UTC by dmersiyanov

2018-09-30 15:50 UTC, PStrelchenko requested changes
Нужны правки.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        val intent = Intent(Intent.ACTION_SENDTO).apply {
Вынеси `dmersiyanov@yandex.ru` в константы - в companion object с const val. 
Да и subject тоже можно вынести. 
Хотя subject на разных языках должен быть разным. 

Пусть лучше по умолчанию темы не будет, либо засунь subject в константку тоже.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +            data = Uri.parse("mailto:")
По поводу построения Intent-а для открытия приложения email-а -- я в канал постил большую простыню, почитай. 
Похоже, что в случае c ACTION_SENDTO более надежным способом открытия приложения является построение URI с `mailto:`. Читать тут - https://medium.com/@cketti/android-sending-email-using-intents-3da63662c58f

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +            putExtra(Intent.EXTRA_EMAIL, email)
Вынеси построение Intent-а для email-а (и всех интентов, которые запускают другие приложения) в ThirdPartyIntentUtils. 

Зачем: уберешь из Activity лишний код, в одно место сложишь методы, относящиеся к построениям Intent-ов, не связанных с твоим приложением.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +            Toast.makeText(this, getString(R.string.error_no_email_app), Toast.LENGTH_SHORT).show()
Вместо Toast можно использовать модный Snackbar - 
https://developer.android.com/reference/android/support/design/widget/Snackbar
https://material.io/design/components/snackbars.html

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +            telegramIntent.data = Uri.parse("http://telegram.me/dmersiyanov")
Вынеси `http://telegram.me/dmersiyanov` в константу + 
я бы перенес метод создания Intent-а для приложения в ThirdPartIntentUtils

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        } catch (e: Exception) {
Придерживайся одного стиля проверки Intent-ов. В одном методе ты проверяешь через resolveActivity, в другом - через try-catch. 
Лучше проверяй через resolveActivity. 

И я бы вынес эту проверку в Utils класс.

То есть получилось бы вот так:

```
val telegramIntent = ThirdPartyIntentUtils.getOpenAppIntent(TELEGRAM_LINK)
if (telegramIntent == null) {
    showErrorSnackbar(getString(R.string.error_no_browser))
} else {
    startActivity(telegramIntent)
}
```

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginStart="32dp"
Размеры - в dimen перенеси. 
Если они будут в dimen-ах, для других размерностей их можно будет переопределять.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginTop="16dp"
Размеры - в dimen. Не буду уже указывать для всех остальных мест, поправь везде, пожалуйста.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/res/layout-land/activity_about.xml
> +            <LinearLayout
Связку LinearLayout > ImageView + TextView можно заменить при помощи одного TextView с compoundDrawable.

Если у тебя возникли проблемы с центрированием текста по вертикали возле иконки -- тогда делай Custom view - наследника LinearLayout. Если сам не разберешься как это сделать, пингани, расскажу. 

Почему на это обращаю внимание - у тебя в верстке много дублирующейся верстки (несколько повторяющихся структур в виде LinearLayout, внутри которого просто разные картинки и разный текст) -- лучше делать ее попроще.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/res/layout-land/activity_about.xml
> +            <View
У тебя две одинаковые вьюхи в верстке - прям один в один. Их можно вынести в один-единственный layout-файл, назвать, скажем, separator - и подключать в этот файл через <include>.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/AndroidManifest.xml
>              <intent-filter>
Только у одной activity должно быть указание, что она главная. У меня на эмуляторе постоянно в качестве главной активити запускалась MainActivity. 
Оставь 

```
<intent-filter>
                <action android:name="android.intent.action.MAIN" />
                 <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
```

Только у AboutActivity и убери intent-filter у MainActivity, или же сделай на MainActivity кнопочку перехода на AboutActivity.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
Переведи класс на Kotlin, раз уж начал все делать на Kotlin-е =) Не забудь, что savedInstanceState - это Bundle?

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/MainActivity.java
> +        setContentView(R.layout.activity_main);
Оставлю комментарий здесь, потому что на бинарных файлах оставлять нельзя -- 

Иконки телеграма и железного человека можно сделать векторными.
Векторная иконка чем хороша - всего один файл, вместо 5 для разных размерностей. 

Читаем вот тут про подключение векторных иконок:

https://developer.android.com/guide/topics/graphics/vector-drawable-resources

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
Не забудь про подключение векторных иконок в этом файле.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/res/layout-land/activity_about.xml
> +<LinearLayout android:orientation="horizontal"
Немного у тебя странно получилось - 
LinearLayout, внутри него ScrollView, внутри него LinearLayout. 

Кажется, что что-то здесь лишнее.

Нужно стараться делать верстку с наименьшей вложенностью. 
В нашем случае, когда у нас нет ConstraintLayout под рукой, это означает, что не надо делать лишней вложенности =)

Написал, а потом увидел, что ты используешь weightSum. Понял, для чего тебе лишний layout - но ты его (в смысле, weightSum) используешь неправильно - у тебя нет ни одной view, которая бы имела размер 0dp =)
Исправляй.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_about.xml
> +<LinearLayout android:orientation="vertical"
В layout-land-е было понятно, зачем используешь вложенность лишнюю (LinearLayout > ScrollView > LinearLayout), а здесь - непонятно. Что-то лишнее, похоже.

2018-09-30 15:50 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_about.xml
> +    <ScrollView
Часть со ScrollView одинаковая и в случае вертикальной, и в случае горизонтальной верстки. 
Значит можно вынести ее в отдельный layout файл и подключать через include.

2018-10-01 19:41 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        val intent = Intent(Intent.ACTION_SENDTO).apply {
сделал

2018-10-01 20:02 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +            putExtra(Intent.EXTRA_EMAIL, email)
вынес логику в getEmailIntent(), но не уверен что понял верно - проверь)

2018-10-01 20:02 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +            Toast.makeText(this, getString(R.string.error_no_email_app), Toast.LENGTH_SHORT).show()
добавил

2018-10-01 20:11 UTC, dmersiyanov commented on app/src/main/AndroidManifest.xml
>              <intent-filter>
да это задел на 3ю домашку был, а потом я вспомнил что нужно в другой ветке - убрал)

2018-10-01 20:12 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
да это задел на 3ю домашку был, а потом я вспомнил что нужно в другой ветке - убрал)

2018-10-06 10:31 UTC, dmersiyanov commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginStart="32dp"
Сделал, но сомневаюсь насколько это удобно. Ибо я люблю когда в лейауте видно размеры и не нужно за ним лезть в другой файл.
В чем профит?)

2018-10-06 10:32 UTC, dmersiyanov commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginTop="16dp"
см. первый комент

2018-10-06 11:47 UTC, dmersiyanov commented on app/src/main/res/layout-land/activity_about.xml
> +            <LinearLayout
Сделал ImageTextView - посмотри, пожалуйста, на сколько адекватно получилось)

2018-10-06 11:48 UTC, dmersiyanov commented on app/src/main/res/layout/activity_about.xml
> +<LinearLayout android:orientation="vertical"
Да, точно. Сделал ScrollView корневым

2018-10-06 11:55 UTC, dmersiyanov commented on app/src/main/res/layout-land/activity_about.xml
> +            <View
вынес и добавляю через include

2018-10-06 12:01 UTC, dmersiyanov commented on app/src/main/res/layout-land/activity_about.xml
> +<LinearLayout android:orientation="horizontal"
хм, странно, пришлось менять вес картинки и основного лейаута местами и получился точно такой же эффект когда layout_width был "match_parent"  а не 0dp)

2018-10-06 12:04 UTC, dmersiyanov commented on app/src/main/res/layout/activity_about.xml
> +    <ScrollView
нет, теперь они не совсем одинаковые т.к я убрал вложенность с вертикальной верстки, в land картинки лежит вне, поэтому мне кажется вынести не получится

2018-10-06 13:30 UTC, dmersiyanov commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
добавил vectorDrawables.useSupportLibrary = true в defaultConfig

2018-10-06 13:34 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.java
> +        setContentView(R.layout.activity_main);
добавил векторную иконку ic_iron_man.xml - прикольно :)

2018-10-06 13:42 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        } catch (e: Exception) {
На сколько я понял тут не получится так сделать т.к проверка такая не работает, студия говорит что (telegramIntent == null) is always false. 
Мы тут пытаемся парсить урл и на сколько я понимаю ошибка только во время парсинга может быть.
В общем код я добавил, подскажи как тут быть.

2018-10-07 12:11 UTC, PStrelchenko requested changes
Правки-правки. Но не очень много

2018-10-07 12:11 UTC, PStrelchenko commented on app/build.gradle
>      implementation 'com.android.support.constraint:constraint-layout:1.1.3'
В этой домашке не должно было быть constraint layout =)

2018-10-07 12:11 UTC, PStrelchenko commented on app/build.gradle
>      testImplementation 'junit:junit:4.12'
Убери пока тестовые зависимости - все равно тесты не пишете

2018-10-07 12:11 UTC, PStrelchenko commented on app/build.gradle
>          testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
Убери пока - все равно тесты пока не пишите

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/AndroidManifest.xml
>              <intent-filter>
Ты так и не убрал здесь intent-filter лишний.

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        } catch (e: Exception) {
Ну, так все правильно - котлин же учитывает то, что ты написал.
У тебя утилитный класс возвращает не `Intent?`, а `Intent` --> котлин думает, что ты всегда возращаешь только `@NonNull` элемент, о чем тебе и сообщает.

Как тут быть - моя идея с переносом функции создания Intent в utils была в том, чтобы ты заодно там проверял, сможет ли устройство открыть этот интент. И если нет -- вернуть null.

```
fun createIntent(context: Context): Intent? {
    val intent = Intent(context).apply {
    
    }
    return if (canResolve) intent else null
}
```

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        // TODO Здесь студия говорит telegramIntent == null is always false
Отписался выше.

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +    companion object {
Я бы всегда помещал `companion object` сверху - это же аналог static-членов в Java. 
Но это как тебе угодно, на самом деле.

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        const val EMAIL = "dmersiyanov@yandex.ru"
отметь константы `private` - ты же их больше нигде не используешь

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/Utils/ThirdPartyIntentUtils.kt
> +package com.dmity.androidacademy.Utils
почему название пакета с большой буквы? это не по java code convention -> исправь на маленькую - `utils`.

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/Utils/ThirdPartyIntentUtils.kt
> +        val telegramIntent = Intent(Intent.ACTION_VIEW)
1) заполнение интента данными - можно сделать в блоке apply - аналогично функции выше
2) сюда еще проверку на то, можно ли открыть приложение

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/Utils/ThirdPartyIntentUtils.kt
> +        return Intent(Intent.ACTION_SENDTO).apply {
У нас тут были нешуточные баталии на тему того, как правильно задавать intent с action = ACTION_SENDTO. 
Вот тут - https://medium.com/@cketti/android-sending-email-using-intents-3da63662c58f - написано, как правильно. 

То, что ты написал - это действительно незадокуметированная возможность в android sdk, которую используют некоторые приложения.

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/Utils/ThirdPartyIntentUtils.kt
> +     fun getEmailIntent(message: String, email: Array<String> = arrayOf(AboutActivity.EMAIL), subject: String = AboutActivity.SUBJECT): Intent {
Перенеси константы EMAIL и SUBJECT сюда - зачем они тебе в AboutActivity

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/Views/ImageTextView.kt
> +class ImageTextView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
Лучше отформатируй код, например вот так:

```
class ImageTextView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
): LinearLayout(context, attrs, defStyleAttr) {

}
```

Читаться проще будет.

2018-10-07 12:11 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/Views/ImageTextView.kt
> +        val attrs = context.obtainStyledAttributes(attrs, R.styleable.ImageTextView)
А вынеси-ка эту штуку в extension функции. Чтобы апи было примерно таким:

```
attrs.extractWithRecycle(id) {

}
```

будет тебе хорошая практика =)

2018-10-07 12:11 UTC, PStrelchenkoHH commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginEnd="16dp"
размеры - вынеси в dimens

2018-10-07 12:11 UTC, PStrelchenkoHH commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginEnd="16dp"
размеры в dimens

2018-10-07 12:11 UTC, PStrelchenkoHH commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginEnd="16dp"
везде размеры - в dimens.
Плюс - вроде по ДЗ размер текста везде 16sp

2018-10-07 12:11 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_about.xml
> +            android:layout_height="225dp"
Всюду размеры - в dimen

2018-10-07 12:11 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_about.xml
> +        <com.dmity.androidacademy.Views.ImageTextView
Общий контент (в land и portrait версиях) можно вынести в один layout файл и подключать через include.

2018-10-07 12:11 UTC, PStrelchenkoHH commented on app/src/main/res/layout/layout_image_text_view.xml
> +        android:layout_width="20dp"
размеры - в dimen.

Плюс - я бы предпочитаемый размер вынес бы в attributes.

2018-10-07 16:17 UTC, dmersiyanov commented on app/build.gradle
>      implementation 'com.android.support.constraint:constraint-layout:1.1.3'
убрал

2018-10-07 16:18 UTC, dmersiyanov commented on app/build.gradle
>          testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
убрал

2018-10-07 16:18 UTC, dmersiyanov commented on app/src/main/AndroidManifest.xml
>              <intent-filter>
Да это кусок третьей домашки, там он убрал, но ок убрал и здесь

2018-10-07 16:24 UTC, dmersiyanov commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginEnd="16dp"
вынес, но 16sp слишком много)

2018-10-07 16:24 UTC, dmersiyanov commented on app/src/main/res/layout/activity_about.xml
> +            android:layout_height="225dp"
вынес

2018-10-07 16:24 UTC, dmersiyanov commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginEnd="16dp"
вынес

2018-10-07 16:25 UTC, dmersiyanov commented on app/build.gradle
>      testImplementation 'junit:junit:4.12'
убрал

2018-10-07 17:04 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +    companion object {
понял

2018-10-07 17:07 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        const val EMAIL = "dmersiyanov@yandex.ru"
сделал

2018-10-07 17:07 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/Utils/ThirdPartyIntentUtils.kt
> +package com.dmity.androidacademy.Utils
переименовал

2018-10-07 17:07 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/Utils/ThirdPartyIntentUtils.kt
> +     fun getEmailIntent(message: String, email: Array<String> = arrayOf(AboutActivity.EMAIL), subject: String = AboutActivity.SUBJECT): Intent {
перенес

2018-10-07 17:07 UTC, dmersiyanov commented on app/src/main/res/layout-land/activity_about.xml
> +                android:layout_marginEnd="16dp"
вынес

2018-10-07 17:07 UTC, dmersiyanov commented on app/src/main/res/layout/activity_about.xml
> +        <com.dmity.androidacademy.Views.ImageTextView
вынес

2018-10-07 18:33 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        // TODO Здесь студия говорит telegramIntent == null is always false
идею понял, переделал)

2018-10-07 18:34 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/Utils/ThirdPartyIntentUtils.kt
> +        val telegramIntent = Intent(Intent.ACTION_VIEW)
исправил

2018-10-07 18:35 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/Views/ImageTextView.kt
> +class ImageTextView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
исправил

2018-10-07 18:37 UTC, dmersiyanov commented on app/src/main/res/layout/layout_image_text_view.xml
> +        android:layout_width="20dp"
вынес

2018-10-07 19:06 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/Views/ImageTextView.kt
> +        val attrs = context.obtainStyledAttributes(attrs, R.styleable.ImageTextView)
добавил в Extentions.kt, но смысла в ней не вижу никакого т.к код никак не сократился. 
А если делаю с attributes.recycle() то приложение падает с Error inflating class com.dmity.androidacademy.views.ImageTextView

2018-10-07 20:31 UTC, PStrelchenko requested changes
Реквестирую ченджи! =)

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/views/ImageTextView.kt
> +        attrs?.let {
Лучше проименуй параметр `let`-блока. Когда он занимает одну строчку - это норм, что ты используешь `it`,  никаких сомнений по поводу того, чем же является `it` не возникает. А когда он занимает несколько строк - тут уже становится не очень понятно. А если внутри одного `let`-а появляется другой `let`...

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/utils/ThirdPartyIntentUtils.kt
> +    const val TELEGRAM_LINK = "http://telegram.me/dmersiyanov"
А почему эта ссылка не `private`?

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_about_content.xml
> +        android:layout_height="225dp"
опять не вынес dimen

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/res/layout/view_separator.xml
> +    android:layout_height="1dp"
И тут не вынес dimen

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/utils/ThirdPartyIntentUtils.kt
> +            data = Uri.parse("mailto:$EMAIL" +
А интерполяцию нельзя использовать? Ну там:

`"mailto:$EMAIL?subject=${Uri.encode(SUBJECT)}&body=${Uri.encode(message)}"`

В одну строчку даже должно влезть, особенно если в отдельный метод вынести

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        if(this.resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
ооочень странная штука. ну, то есть, зачем тебе скрывать my_picture именно в горизонтальной ориентации?

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        val intent = ThirdPartyIntentUtils.getEmailIntent(message, context = this)
если используешь именованные параметры, лучше использовать их на каждом аргументе. станет понятнее читать. А то неясно, зачем именно context указал.

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_about_content.xml
> +    <ImageView
Зачем тебе в "общем" контенте картинка my_picture?.. Она-то как раз у тебя меняется от ориентации к ориентации!
Моя идея была вот в чем -- ты в вертикальной ориетации оставляешь картинку, под ней - общий контент со скроллом, в горизонтальной - тоже картинка, а потом - общий контент со скроллом.

2018-10-07 20:31 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_about_content.xml
> +    <ImageView
Ну, по крайней мере, я понял, зачем ты скрываешь картинку в горизонтальной ориентации.
В общем, так не должно было быть

2018-10-08 08:26 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/ThirdPartyIntentUtils.kt
> +    const val TELEGRAM_LINK = "http://telegram.me/dmersiyanov"
забыл)

2018-10-08 08:27 UTC, dmersiyanov commented on app/src/main/res/layout/activity_about_content.xml
> +        android:layout_height="225dp"
вынес

2018-10-08 08:27 UTC, dmersiyanov commented on app/src/main/res/layout/view_separator.xml
> +    android:layout_height="1dp"
вынес

2018-10-08 08:29 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/views/ImageTextView.kt
> +        attrs?.let {
проименовал

2018-10-08 08:35 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/ThirdPartyIntentUtils.kt
> +            data = Uri.parse("mailto:$EMAIL" +
вынес

2018-10-08 08:37 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        val intent = ThirdPartyIntentUtils.getEmailIntent(message, context = this)
забыл убрать имя после того переделал метод - исправил

2018-10-08 09:02 UTC, dmersiyanov commented on app/src/main/res/layout/activity_about_content.xml
> +    <ImageView
получилось) исправил

2018-10-08 09:02 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        if(this.resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
удалил)

2018-10-10 13:41 UTC, PStrelchenko approved these changes
Все гут

2018-10-10 13:41 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/utils/ThirdPartyIntentUtils.kt
> +    private const val SUBJECT = "Деловое предложение"
Меня тут недавно заставили задуматься о том, а что будет, если ты переключишь локаль? У тебя на английской локали тема отправляемого сообщения будет на русском. Для упрощения локализации - можно оставить SUBJECT в strings.xml. 
А если поместить subject в strings.xml - почему бы и email там же рядом не положить =)

Это размышления вслух, не призыв к действию.

2018-10-11 06:47 UTC, merged