Exercise 3
dmersiyanov/AndroidAcademy pull request #2
Opened 2018-10-13 15:07 UTC by dmersiyanov

2018-10-14 14:53 UTC, PStrelchenko requested changes
Реквестирую ченджи + доработки домашки

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/build.gradle
> +    androidExtensions {
Это еще зачем? Чтобы `Parcelable` ручками не писать?.. 
Можно было бы просто имплементировать `Serializable` - и вообще проблем не иметь =)

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
Ради интереса - проверял ли на `release` версии приложения?

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +        item.let {
Если используешь `lateinit` переменную, `let` уже не нужен.

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +        const val ITEM_DATA = "item_data"
Модификатор `private` можно добавить

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +        fun display(activity: AppCompatActivity, item: NewsItem) {
можно передавать вместо `AppCompatActivity` обычный `Context`. 
Для чего - для открытия через `deep link`, например.

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +//        news_rv.addItemDecoration(DividerItemDecoration(this, layoutManager.orientation))
Почему закомментировал? =)

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        val layoutManager = GridLayoutManager(this, if (isPortrait()) 1 else 2)
можно не выделять в отдельную переменную, сразу написать

`news_rv.layoutManager = GridLayout ... `

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        news_rv.layoutManager = layoutManager
Я бы написал так:

```with(news_rv) {
    layoutManager = Grid ...
    adapter = NewsListAdapter( ... )
}```

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        news_rv.layoutManager = layoutManager
Симпатичнее, что ли.

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        Toast.makeText(this, item.title, Toast.LENGTH_SHORT).show()
`Toast`-ы на одной activity, на другой - snackbar --> юзай один стиль. Либо так, либо иначе. Иначе просто некрасиво

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +    private fun isPortrait(): Boolean {
Вынеси в `ActivityExt.kt` - файл extension функций, связанных с `Activity`.

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +    : RecyclerView.Adapter<NewsListAdapter.ViewHolder>() {
Оставь лучше на той же строчке, где и закрывающая скобка стоит

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +        return ViewHolder(LayoutInflater.from(parent.context).inflate(R.layout.news_item, parent, false))
Я тут выяснил, что сам на автомате пишу LayoutInflater так, чтобы его получить лишь 1 раз - в конструкторе. 
Чем лучше вариант, который есть у тебя сейчас -- не ошибешься никогда с контекстом, из которого получаешь layout infalter. Но зато каждый раз получаешь новый inflater, но то не обязательно.

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +        return ViewHolder(LayoutInflater.from(parent.context).inflate(R.layout.news_item, parent, false))
По поводу `viewType` -- где у тебя использование разных viewType-ов? По заданию требовалось сделать хотя бы 2 разные карточки

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/models/Models.kt
> +class Category(val id: Int,
Не экономьте на файлах, выноси разные классы в разные файлы.

Случай с ViewHolder - это исключение =) Потому что он относится ТОЛЬКО к RecyclerView

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/utils/DataUtils.kt
> +        val darwinAwards = Category(1, "Darwin Awards")
Другим ребятам рассказывал и тебе расскажу, что Category похожа на enum. Почему бы не использовать тут enum?

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.recyclerview.widget.RecyclerView
Если RecylerView - твой единственный View, то зачем тут LinearLayout, который ничего не делает? Был бы у него паддинг, или background какой-  было бы понято. А так - неясно.

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_main.xml
> +        android:clipToPadding="true"
Зачем добавил этот параметр?
Это вопрос, а не требование сменить.

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/res/layout/news_item.xml
> +    <RelativeLayout
А почему бы Constraint не заюзать? Уверен, что получилась бы вложенность == 1

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/res/menu/menu_list.xml
> +        android:id="@+id/action_about"
Рекомендуют добавлять orderInCaterogy всегда, даже если элемент всего один

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
И не увидел, где бы ты тут использовал annotation processing, подсвети, что я упустил

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +             news_date.text = item.publishDate.toString()
Не увидел нигде форматирования даты, как в new your times. Вэйр из ит?

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
>      private fun setupToolbar() {
Я бы все-таки советовал выдерживать хоть какой-то code style. Приватные функции, например, после всех override-функций писать.

2018-10-14 14:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +    private fun getIntentData() {
Эту штуку я бы вообще переписал бы на lazy блок:
```
private val item: NewsItem? by lazy {
    intent?.extras?.getParcelable<NewsItem>(ITEM_DATA)
}
```

А потом везде можно юзать просто через `item`.

2018-10-14 18:07 UTC, dmersiyanov commented on app/build.gradle
> +    androidExtensions {
Ну да? Что удалять ? :)

2018-10-14 18:10 UTC, dmersiyanov commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
1) На release пишет что Error: The apk for your currently selected variant (app-release.apk) is not signed. Please specify a signing configuration for this variant (release). Не совсем понял про что речь.

2) annotationProcessor - точно, убрал

2018-10-14 18:12 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +        item.let {
сделал через with()

2018-10-14 18:12 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +        fun display(activity: AppCompatActivity, item: NewsItem) {
поменял

2018-10-14 18:13 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +        const val ITEM_DATA = "item_data"
добавил

2018-10-14 18:14 UTC, dmersiyanov commented on app/src/main/res/menu/menu_list.xml
> +        android:id="@+id/action_about"
добавил

2018-10-14 18:16 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
>      private fun setupToolbar() {
да, хорошее замечание)

2018-10-14 18:19 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +    private fun getIntentData() {
хм, а тут красиво не получается т.к везде где я юзаю через item нужно ругается что нужно передать not-null тип.
Как быть?

2018-10-14 18:23 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +//        news_rv.addItemDecoration(DividerItemDecoration(this, layoutManager.orientation))
да там полоска же появляется серая, мне она не нравится в задании ее тоже нет) 
удалил полностью

2018-10-14 18:23 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        val layoutManager = GridLayoutManager(this, if (isPortrait()) 1 else 2)
а он мне нужен был для addItemDecoration, но я хочу от него отказаться)

2018-10-14 18:25 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        news_rv.layoutManager = layoutManager
не совсем понял как именно, но я убрал переменную для layoutManager

2018-10-14 18:25 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        Toast.makeText(this, item.title, Toast.LENGTH_SHORT).show()
а блин, забыл убрать, это было для теста только) убрал

2018-10-14 18:28 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +    private fun isPortrait(): Boolean {
вынес

2018-10-14 18:28 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +    : RecyclerView.Adapter<NewsListAdapter.ViewHolder>() {
поправил

2018-10-14 18:30 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/models/Models.kt
> +class Category(val id: Int,
разбил на два файла

2018-10-14 18:33 UTC, dmersiyanov commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.recyclerview.widget.RecyclerView
Блин и правда - открыл Америку. Я тупо не знал что RecyclerView может быть корневым)

2018-10-14 18:38 UTC, dmersiyanov commented on app/src/main/res/layout/activity_main.xml
> +        android:clipToPadding="true"
в данном случае видимо незачем) почитал зачем его используют и тоже не понял зачем он тут - удалил

2018-10-15 19:06 UTC, dmersiyanov commented on app/src/main/res/layout/news_item.xml
> +    <RelativeLayout
так и вышло) - добавил news_item_constrained.xml

2018-10-15 19:19 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/DataUtils.kt
> +        val darwinAwards = Category(1, "Darwin Awards")
добавил Categories.kt

2018-10-15 20:07 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +             news_date.text = item.publishDate.toString()
просмотрел) запилил в DateUtils

2018-10-20 08:57 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +        return ViewHolder(LayoutInflater.from(parent.context).inflate(R.layout.news_item, parent, false))
добавил через AdapterDelegates

2018-10-20 12:30 UTC, PStrelchenko requested changes
Реквестирую ченджи.

2018-10-20 12:30 UTC, PStrelchenko commented on app/build.gradle
> +    androidExtensions {
Нет, не надо.

2018-10-20 12:30 UTC, PStrelchenko commented on app/src/main/AndroidManifest.xml
> +        </activity>
AboutActivity - пустой тэг, можно закрыть его через `/>`

2018-10-20 12:30 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +    private fun setupScreen() {
Да уж. Дичь, Дима =) 

Смотри:
1 - Идея AdapterDelegate была в упрощении работы именно с RecyclerView. И вне него - это просто переусложнение логики отображения. То есть, если ты хочешь получить профит от AdapterDelegate именно на этом экране, то тебе стоит затянуть в этот экран RecyclerView. Правда, учитывая, что у тебя на этом конкретном экране только один вид View (ну то есть я не увидел, например, разницы между кодом `setupData` для `NewsItem` и `AnimalItem`), то смысла тащить сюда Recycler я не вижу. 

2 - Тебе самому не кажется, что если две модели используют одни и те же поля, одни и те же методы, нужно выделить для них единый интерфейс или единый базовый класс?

3 - Прикольно, что решил объявить функции внутри другой функции =) Но по-моему, это немного усложняет чтение кода. Пока доберешься до сути `setupScreen`, тебе надо еще прочитать кучу доп.кода. Внимание рассеивается. Не нужно менять, если тебе норм =) Это мое личное имхо.

2018-10-20 12:30 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        news_rv.layoutManager = GridLayoutManager(this, if (isPortrait()) 1 else 2)
Не рекомендую оставлять "магические числа" в коде - обзови их какими-то константами. Если бы я в первый раз читал этот код, меня бы чиселки 1 и 2 немного смутили бы

2018-10-20 12:30 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +class AnimalAdapterDelegate(activity: Activity, private val clickListener: (DisplayableItem) -> Unit):  AdapterDelegate<List<DisplayableItem>>() {
Уверен, что тебе нужно именно `Activity` здесь? Или же обычного `context` здесь достаточно?

2018-10-20 12:30 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +class AnimalAdapterDelegate(activity: Activity, private val clickListener: (DisplayableItem) -> Unit):  AdapterDelegate<List<DisplayableItem>>() {
В библиотеке DelegateAdapter есть класс `AbsListItemDelegateAdapter`, который позволит тебе не писать каждый раз `items[position]`, а будет пробрасывать тебе только нужные элементы в твои методы - заюзай его.

2018-10-20 12:30 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +    internal class AnimalVH(itemView: View): RecyclerView.ViewHolder(itemView) {
Я бы порекомендовал создать базовый класс для всех ViewHolder-ов и всегда использовать именно его:

`class BaseViewHolder(itemView: View): RecyclerView.ViewHolder(itemView)`

Тогда не придется писать доп класс для ViewHolder-а каждый раз. Все равно, благодаря delegate adapter, в нем остается всего один метод. 

-->
```
override fun onCreateViewHolder(parent: ViewGroup): RecyclerView.ViewHolder {
        return BaseViewHolder(inflater.inflate(layoutId, parent, false))
 }
```

Огонь же.

2018-10-20 12:30 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +            = (holder as AnimalVH).bind(items[position], clickListener)
А здесь можно просто написать код для биндинга напрямую -- тогда и не нужен никакой каст к AnimalVH. 
Фишка ведь delegate adapter-а еще и в том, что на Котлине можно написать реально компактный классик =) 

```
with(holder.itemView) {
           newsTitle.text = item.title
            newsCategory.text = item.newsCategory?.category
            newsText.text = item.previewText
            newsDate.text = DateUtils.formatDateForNews(item.publishDate, itemView.context)
            newsImage.loadImg(item.imageUrl)
             setOnClickListener { listener(item) }
}
```

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/adapters/GenericNewsAdapterDelegate.kt
> +class GenericNewsAdapterDelegate(activity: Activity, private val clickListener: (DisplayableItem) -> Unit): AdapterDelegate<List<DisplayableItem>>() {
Аналогичные замечания. как и к AnimalDelegateAdapter.

Я бы сделал, кстати, еще базовый класс, который наследовал бы AbsListItemAdapterDelegate -> и он бы имел поле `inflater` + метод для наследников вида:

```
protected fun fromLayoutId(@LayoutId layoutId: Int, parent: ViewGroup): BaseViewHolder {
    return inflater.inflate(layoutId, parent)
}
```

В общем, накрутить можно кучу всего ) И благодаря котлину все будет выглядеть компактно и удобно. 
А сейчас это, по сути, тот же самый `RecyclerView.Adapter`, только в профиль

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsAdapter.kt
> +class NewsAdapter(activity: Activity, news: List<DisplayableItem>, clickListener: (DisplayableItem) -> Unit) : ListDelegationAdapter<List<DisplayableItem>>() {
Действительно здесь нужен `Activity`? Похоже, что нет =)

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +class NewsListAdapter(private val items: List<NewsItem>,
Ммм, так может удалить класс, если даже на это есть TODO? =)
Плюс класс не используется.

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/models/Category.kt
> +class Category(val id: Int,
Класс не используется. Нужен ли он?

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/utils/DateUtils.kt
> +        return when(DateUtils.isToday(date.time)) {
Можно посмотреть, как Сережа Рябов сделал форматирования даты:
https://github.com/Android-Academy-MSK/NYTimes/commit/90df3638d23bd870dfbfebc4195373ad06e5e8c4

Там прям в одну строчку все решается.

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/utils/Extentions.kt
> +fun Activity.isPortrait(): Boolean {
Я бы лучше разнес extension-функции, связанные с разными классами, в разные файлы. Просто иначе получается каша из кучи разных функций, эдакий винегрет =) 
Кстати, `Activity.isPortrait()` опять же можно заменить на `Context.isPortrait()`. И это по-прежнему будет работать

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/utils/Extentions.kt
> +    if (TextUtils.isEmpty(imageUrl)) {
Необязательно юзать android-ную функцию TextUtils.isEmpty -> в котлине же есть свой набор:

`imageUrl.isBlank()` - здесь подходит

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_main.xml
> +<androidx.recyclerview.widget.RecyclerView
Файл называется `activity_main`, а используешь в `NewsListActivity` =)

2018-10-20 12:30 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_main.xml
> +    tools:context=".NewsListActivity">
Пустой тэг -- закрываем через `/>`

2018-10-20 18:12 UTC, dmersiyanov commented on app/src/main/AndroidManifest.xml
> +        </activity>
закрыл

2018-10-20 18:14 UTC, dmersiyanov commented on app/src/main/res/layout/activity_main.xml
> +    tools:context=".NewsListActivity">
закрыл

2018-10-20 18:15 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/Extentions.kt
> +    if (TextUtils.isEmpty(imageUrl)) {
забыл) исправил

2018-10-20 18:17 UTC, dmersiyanov commented on app/src/main/res/layout/activity_main.xml
> +<androidx.recyclerview.widget.RecyclerView
Переименовал в MainActivity)

2018-10-20 18:17 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsListAdapter.kt
> +class NewsListAdapter(private val items: List<NewsItem>,
удалил

2018-10-20 18:18 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/models/Category.kt
> +class Category(val id: Int,
удалил

2018-10-20 18:24 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/Extentions.kt
> +fun Activity.isPortrait(): Boolean {
Идею я понял и изменил на контекст. Тут вроде пока не много их и хочется оставить в одном файле) Ок?)

2018-10-20 18:37 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsListActivity.kt
> +        news_rv.layoutManager = GridLayoutManager(this, if (isPortrait()) 1 else 2)
вынес в integers.xml

2018-10-20 19:03 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsDetailsActivity.kt
> +    private fun setupScreen() {
2 - выделил класс как ты подсказал
3 - ну мне норм вроде, делаю так когда функция нужна только единожды, но это потеряло актуальность когда появился общий абстрактный класс)

2018-10-20 19:49 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +class AnimalAdapterDelegate(activity: Activity, private val clickListener: (DisplayableItem) -> Unit):  AdapterDelegate<List<DisplayableItem>>() {
Да, можно и context. Просто в примере передавали активити) 
В общем я отказался от идеи передать туда что-либо и достаю контекст вот так  `inflater = LayoutInflater.from(parent.context)`

2018-10-20 19:49 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsAdapter.kt
> +class NewsAdapter(activity: Activity, news: List<DisplayableItem>, clickListener: (DisplayableItem) -> Unit) : ListDelegationAdapter<List<DisplayableItem>>() {
В общем я отказался от идеи передать туда что-либо и достаю контекст вот так inflater = LayoutInflater.from(parent.context)

2018-10-20 20:01 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +    internal class AnimalVH(itemView: View): RecyclerView.ViewHolder(itemView) {
Да, огонь) если я правильно тебя понял))
Сделал класс BaseViewHolder и написал вопрос

2018-10-20 20:02 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +            = (holder as AnimalVH).bind(items[position], clickListener)
да, получилось компактно, тем более что весе это в базовом VH)

2018-10-20 20:14 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/GenericNewsAdapterDelegate.kt
> +class GenericNewsAdapterDelegate(activity: Activity, private val clickListener: (DisplayableItem) -> Unit): AdapterDelegate<List<DisplayableItem>>() {
Добавил - получилось круто)

2018-10-20 20:15 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +class AnimalAdapterDelegate(activity: Activity, private val clickListener: (DisplayableItem) -> Unit):  AdapterDelegate<List<DisplayableItem>>() {
заюзал

2018-10-20 20:21 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/DateUtils.kt
> +        return when(DateUtils.isToday(date.time)) {
тут мне кажется у меня лучше реализовано либо я чего-то не понимаю)) потому что код Сергея форматирует только в один единственный вид дату - Sep 26, 10:34, например.

А у меня учитываются варианты:
1) Новость вышла сегодня и тогда будет показано кол-во часов с ее публикации и время
2) Новость вышла вчера - будет показано Yesterday и время публикации
3) Если новость старше чем вчерашняя то обычный формат - дата + время публикации (как у Сергея)

Таким образом у нас было в задании, разве нет?)

2018-10-20 21:25 UTC, PStrelchenko requested changes
И, надеюсь, последний реквест ченджей.

2018-10-20 21:25 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +    override fun onCreateViewHolder(parent: ViewGroup): BaseViewHolder = BaseViewHolder(fromLayoutId(R.layout.item_animal_constrained, parent))
Здесь я имел в виду, что ты методом `fromLayoutId` уже создаешь `BaseViewHolder`, ну да ладно

2018-10-20 21:25 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +    override fun onCreateViewHolder(parent: ViewGroup): BaseViewHolder = BaseViewHolder(fromLayoutId(R.layout.item_animal_constrained, parent))
Дим, ты меня не понял.
`BaseViewHolder` - это должен был быть вообще пустой класс. Вообще. То есть вот такой:

```
class BaseViewHolder(itemView: View): RecyclerView.ViewHolder(itemView)
```

Вся магия binding-а должна была остаться в делегате. Иначе смысл его вообще заводить-то? Только ради `isForViewType` метода?

2018-10-20 21:25 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/base/BaseAdapterDelegate.kt
> +    protected fun fromLayoutId(layoutId: Int, parent: ViewGroup): View {
Этот метод должен был вернуть `BaseViewHolder`, чтобы облегчить тебе жизнь =)

2018-10-20 21:25 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/base/BaseViewHolder.kt
> +    // TODO Я правильно понимаю, что у нас будут появляться еще ViewHolder'ы если у нас будут использованы другие модели данных?
Неправильно понял. 
Этот класс должен был быть пустым вообще.

Вся логика привязки данных к view должна была остаться в отдельных делегатах, в методе `onBindViewHolder`. То есть например для твоего GenericNewsItemDelegate у тебя был бы такой метод:

```
override fun onBindViewHolder(
    item: GenericNewsItem, 
    holder: BaseViewHolder, 
    payloads: MutableList<Any>
) {
    with (holder.itemView) {
        newsTitle.text = item.title
        newsCategory.text = item.newsCategory.category
        newsText.text = item.previewText
        newsDate.text = DateTimeUtils.formatDateForNews(item.publishDate, context)
        newsImage.loadImg(item.imageUrl)

        setOnClickListener { clickListener.invoke(item) }
    }
}
```

2018-10-20 21:25 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/utils/DateTimeUtils.kt
> +        return when(DateUtils.isToday(date.time)) {
Посмотри, все-таки, внимательнее в описание функции `DateUtils.getRelativeDateTimeString`.
Она умеет возвращать все, что ты описал.

2018-10-21 09:23 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +    override fun onCreateViewHolder(parent: ViewGroup): BaseViewHolder = BaseViewHolder(fromLayoutId(R.layout.item_animal_constrained, parent))
переделал

2018-10-21 09:24 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/AnimalAdapterDelegate.kt
> +    override fun onCreateViewHolder(parent: ViewGroup): BaseViewHolder = BaseViewHolder(fromLayoutId(R.layout.item_animal_constrained, parent))
да, согласен, в общем все косяки из-за того что не понял зачем нужен BaseViewHolder.

2018-10-21 09:24 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/BaseAdapterDelegate.kt
> +    protected fun fromLayoutId(layoutId: Int, parent: ViewGroup): View {
исправил)

2018-10-21 09:24 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/BaseViewHolder.kt
> +    // TODO Я правильно понимаю, что у нас будут появляться еще ViewHolder'ы если у нас будут использованы другие модели данных?
исправил

2018-10-21 09:57 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/DateTimeUtils.kt
> +        return when(DateUtils.isToday(date.time)) {
блин, ну да крутая тема) там есть только одна проблема, что нельзя локаль проставить нормальным способом и у нас сейчас получается контент на английском, а время на русском - я так не хочу делать)

Затянул в проект этот метод и поменяю если будет апишка новости на русском отдавать. Окей?

2018-10-21 11:54 UTC, PStrelchenko approved these changes
Поехали дальше - к 4 ДЗ

2018-10-21 12:48 UTC, merged