Exercise 4 threads
dmersiyanov/AndroidAcademy pull request #4
Opened 2018-10-21 12:54 UTC by dmersiyanov

2018-10-25 20:08 UTC, PStrelchenko requested changes
Реквестирую ченджи!

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        Single.just(DataUtils.generateNews())
Угадай, что будет, если кто-то изменит код `generateNews` и случайно вернет `null`? =)
Будет большой "пубумс". 
Замени на вызов `fromCallable`. Будет шанс поймать ошибку.

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                .delay(2, TimeUnit.SECONDS)
Магические числа - в константы! =) В companion object.

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                .subscribe({
Когда пишешь блоки кода, занимающие больше 1 строчки, лучше проименовать параметр `it`    во что-то более осмысленное. Это просто "имхо", ничего личного =)

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                    it.printStackTrace()
Здесь аналогично про `it`, но править необязательно

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                    it.printStackTrace()
Хотя ошибку я бы залогировал через Log.e.

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +    override val mDisposable: CompositeDisposable = CompositeDisposable()
Когда я вижу префикс `m`, просматривая код в Android Studio, у меня дергается глаз =) 
Это такой анахронизм, который меня всегда бесил в код-стайле Android-а =) От него все постепенно отказываются, потому что "ну какой смысл делать префикс `m`, если с подсветкой кода и так видно все константы, все поля и тд, и тп?". 
Убери =)

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +    override fun initUx() {
Честно говоря, до сих пор не понимаю, зачем ты выделил эти две функции - `initUi` и `initUx`. И как ты отличаешь `UI` от `UX` =) 
Не кажется, что проще было бы просто все запихнуть в `onCreate`? Тем более что на функции ты поделил все и так, а с kotlin-android-extensions кода меньше, чем в java.

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        getNews()
Получается, что при перевороте экрана у тебя запрос каждый раз умирает и начинается заново? Это не очень круто. И представь, если у тебя бы было много запросов на сервер.

Допиши логику сохранения запроса при перевороте экрана. 
Можешь воспользоваться чем угодно - Loaders, Moxy, ViewModel из Architecture components. 

Я б попробовал последнее =)

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                .doOnSubscribe {
Не увидел у тебя глобального обработчика ошибок для Rx-а. 

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

А он нужен.

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        rvNews.layoutManager = if (isPortrait()) LinearLayoutManager(this)
Если у тебя `if` не помещается в одну строчку, лучше выдели его блоки в фигурные скобки - так будет уверенность, что выполняется только то, что ты написал.

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        adapter = NewsAdapter(DataUtils.generateNews()) { onNewsItemClick(it) }
Воу-воу, новости должны приходить из бекграунда. А ты уже записываешь какие-то новости в адаптер.

2018-10-25 20:08 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +    open fun showError(show: Boolean) {}
Текст ошибки всегда будет один и тот же? Даже на разных экранах? Почему спрашиваю, потому что ты сделал базовую активити, от которой потом будешь все наследовать. А на разных экранах наверняка будут разные ошибки.

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/base/SubscriptionsHolder.kt
> +    val mDisposable: CompositeDisposable
Вижу префикс `m` - прям глаз дергается =) Убери. Это действительно анахронизм. 
И виноват чувак, написавший это - https://habr.com/post/333596/

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/base/SubscriptionsHolder.kt
> +    val mDisposable: CompositeDisposable
Кстати, имя этого поля немного смущает - вроде бы и `CompositeDisposable`, а называется как одиночный disposable, как будто это какая-то одиночная подписка. Лучше переименуй, будет понятнее, что это именно composite. 

З.Ы. За использование extension function, которая добавляет `Disposable` в composite - хвалю, выглядит клево, не так ли?

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/base/SubscriptionsHolder.kt
> +        mDisposable.clear()
А почему не `dispose`?

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_main.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Зачем тут `RelativeLayout`? У тебя видимым элементом в каждый момент времени является только один элемент --> можно заменить на `FrameLayout`. И верстка проще станет чуток. Меньше атрибутов писать.

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_main.xml
> +        android:visibility="visible"
Не забываем `ctrl + alt + L` нажимать + все элементы по умолчанию Visible, не нужно это специально указывать. Думаю, забыл после тестирования верстки убрать

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_main.xml
> +        android:clipToPadding="true"
А зачем тут этот атрибут?

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/res/layout/view_error_stub.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
Не забываем делать `ctrl + alt + L` - атрибуты отсортируются.

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/res/values/dimens.xml
> +    <dimen name="top_margin">150dp</dimen>
А где эта штука используется? Не увидел.

2018-10-25 20:08 UTC, PStrelchenkoHH commented on app/src/main/res/values/strings.xml
> +    <string name="error_loading">Ошибка загрузки</string>
Текст на русском в дефолтном `strings.xml`.

2018-10-28 11:02 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        Single.just(DataUtils.generateNews())
не знал этого, круто! пофиксил

2018-10-28 11:08 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                .delay(2, TimeUnit.SECONDS)
вынес

2018-10-28 11:10 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                .subscribe({
Тут я держу в голове что если вдруг появится let или еще что-то где есть свой it, то нужно проименовать, пока не знаю насколько это черевато)

2018-10-28 11:11 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                    it.printStackTrace()
добавил

2018-10-28 11:12 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +    override val mDisposable: CompositeDisposable = CompositeDisposable()
ну да странно, убрал)

2018-10-28 11:14 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +    override fun initUx() {
initUi - инициализация вьюшек, а initUx - листенеры - кажется в этом есть логика)

Мне просто удобнее так, понятно что где искать. 

Сейчас кода меньше было бы без них, но если экран большой то будет профит на мой взгляд)

2018-10-28 11:15 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        adapter = NewsAdapter(DataUtils.generateNews()) { onNewsItemClick(it) }
а блин, это просто проглядел

2018-10-28 11:21 UTC, dmersiyanov commented on app/src/main/res/layout/activity_main.xml
> +        android:visibility="visible"
нажал, убрал

2018-10-28 11:22 UTC, dmersiyanov commented on app/src/main/res/layout/activity_main.xml
> +        android:clipToPadding="true"
да он ни к чему вроде))

2018-10-28 11:22 UTC, dmersiyanov commented on app/src/main/res/layout/view_error_stub.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
сделал

2018-10-28 11:24 UTC, dmersiyanov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="top_margin">150dp</dimen>
да, и правда

2018-10-28 11:37 UTC, dmersiyanov commented on app/src/main/res/values/strings.xml
> +    <string name="error_loading">Ошибка загрузки</string>
добавил переводы

2018-10-28 11:38 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        rvNews.layoutManager = if (isPortrait()) LinearLayoutManager(this)
добавил скобки

2018-10-28 11:39 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/SubscriptionsHolder.kt
> +    val mDisposable: CompositeDisposable
убрал

2018-10-28 11:39 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/SubscriptionsHolder.kt
> +    val mDisposable: CompositeDisposable
Согласен. Переименовал.

Ну да круто)

2018-10-28 11:44 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/SubscriptionsHolder.kt
> +        mDisposable.clear()
Причина есть :) 

> 
dispose() means that you will no longer be able to add disposables to that composite disposable, clear() means you can - it just clears the disposables that are currently held within the instance.
> 

В моем понимании эта штука по идее должна использоваться в презентере и нам нужно будет добавлять туда новые подписки. Но в случае с активностью можно и dispose разницы по идее нет. Так?

2018-10-28 11:49 UTC, dmersiyanov commented on app/src/main/res/layout/activity_main.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Поменял

2018-10-28 11:55 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +    open fun showError(show: Boolean) {}
Ну пока да, потому что мы делаем просто ошибку загрузки без проверки статуса http запроса.

Но если мы заходим другой текст с ошибкой, что мешает сетить его в методе showError() в каждом конкретно случае например?

2018-10-28 12:56 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                .doOnSubscribe {
Я добавил в свой класс наследник Application

` RxJavaPlugins.setErrorHandler { Log.e("RxJavaPlugins.onError", it.message) }`

2018-10-28 15:53 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        getNews()
Добавил NewsViewModel, но не уверен что все верно.

Подебажил и убедился что к DataUtils.generateNews() обращаемся только единожды, но выглядит странновато)

2018-10-29 07:04 UTC, PStrelchenko requested changes
Реквест ченджей

2018-10-29 07:04 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        RxJavaPlugins.setErrorHandler(emptyConsumer());
Это нужно устанавливать 1 раз за все приложение --> например, в Application классе.

2018-10-29 07:04 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                .doOnSubscribe {
По ссылке советовали написать вот такой:

```
RxJavaPlugins.setErrorHandler(e -> {
    if (e instanceof UndeliverableException) {
        e = e.getCause();
    }
    if ((e instanceof IOException) || (e instanceof SocketException)) {
        // fine, irrelevant network problem or API that throws on cancellation
        return;
    }
    if (e instanceof InterruptedException) {
        // fine, some blocking code was interrupted by a dispose call
        return;
    }
    if ((e instanceof NullPointerException) || (e instanceof IllegalArgumentException)) {
        // that's likely a bug in the application
        Thread.currentThread().getUncaughtExceptionHandler()
            .handleException(Thread.currentThread(), e);
        return;
    }
    if (e instanceof IllegalStateException) {
        // that's a bug in RxJava or in a custom operator
        Thread.currentThread().getUncaughtExceptionHandler()
            .handleException(Thread.currentThread(), e);
        return;
    }
    Log.warning("Undeliverable exception received, not sure what to do", e);
});
```

И да - у тебя приложенька не должна падать в случае, если ты отписался от какого-то observable-а, а получил какое-то исключение.
Мы добавляем такой обработчик, чтоб не словить какой-то краш от rx-цепочки + узнать об исключениях, которые все-таки случились.

2018-10-29 07:04 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/NewsApp.kt
> +        RxJavaPlugins.setErrorHandler { Log.e("RxJavaPlugins.onError", it.message) }
Обычно всю добавочную логику пишут после `super.onCreate`.

2018-10-29 07:04 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +    open fun showError(show: Boolean) {}
Получается, что твоя View знает о какой-то логике приложения. Типо - вот в этом конкретном случае, покажи такой-то текст, иначе - вот такой. 
А View, в конечном итоге, должна получиться как можно более тупой. Поэтому, имхо, лучше добавить `fun showError(errorMessage: String, show: Boolean)`

2018-10-29 07:04 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +    override fun initUx() {
Хорошо, что тебе понятнее =)

2018-10-29 07:04 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/utils/DataUtils.kt
> +    fun generateNews(): List<DisplayableItem>? {
Эта функция у тебя вроде возвращает список ненулабельный. Зачем тебе здесь nullable?

2018-10-29 07:04 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/utils/DataUtils.kt
>          val news = ArrayList<DisplayableItem>()
О, эту штуку не заметил --> замени на `mutableListOf`. Суть не изменится, а будет более kotlin-way что ли.

2018-10-29 07:04 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/viewModel/NewsViewModel.kt
> +    private var news: MutableLiveData<List<DisplayableItem>>? = null
Мне кажется, вот так должно сработать:
(заодно от !! избавишься)
```
private val newsLiveData = MutableLiveData<List<DisplayableItems>?>(null)

fun getNews(): LiveData<List<DisplayableItem>> {
    if (newsLiveData.value == null) {
        newsLiveData.value = DataUtils.generateNews()
    }

    return newsLiveData
}
```

2018-10-29 07:04 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        Flowable.fromPublisher(LiveDataReactiveStreams.toPublisher(this, viewModel.getNews()))
Здесь не нужен `Flowable`, нужен `Single`. Ты же один event получаешь, а потом его обрабатываешь.

2018-10-29 18:39 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/AboutActivity.kt
> +        RxJavaPlugins.setErrorHandler(emptyConsumer());
это забыл убрать)

2018-10-29 18:50 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsApp.kt
> +        RxJavaPlugins.setErrorHandler { Log.e("RxJavaPlugins.onError", it.message) }
поправил

2018-10-29 18:51 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/DataUtils.kt
> +    fun generateNews(): List<DisplayableItem>? {
да я тестировал, когда написал что будет если там придет null и забыл убрать)

2018-10-29 18:51 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/DataUtils.kt
>          val news = ArrayList<DisplayableItem>()
ок

2018-10-29 19:08 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/viewModel/NewsViewModel.kt
> +    private var news: MutableLiveData<List<DisplayableItem>>? = null
так не вышло, сделал через проверку 
`news.value == null`

2018-10-29 19:12 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        Flowable.fromPublisher(LiveDataReactiveStreams.toPublisher(this, viewModel.getNews()))
Это понятно, но нигде не нашел туториала как получить single, в итоге реализовал через http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#firstOrError--

2018-11-03 07:24 UTC, PStrelchenko requested changes
И еще одни изменения - ради более-менее правильного использования ViewModel

2018-11-03 07:24 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        Flowable.fromPublisher(LiveDataReactiveStreams.toPublisher(this, viewModel.getNews()))
Ок

2018-11-03 07:24 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        private const val DELAY: Long = 2
`private const val DELAY = 2L`

2018-11-03 07:24 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/NewsApp.kt
> +    @SuppressLint("LongLogTag")
А что ты сапресишь? Не увидел

2018-11-03 07:24 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                    Log.e(this.javaClass.simpleName, it.message)
Для тэгов лучше завести отдельное поле, потому что после обфускации название класса превратится в тыкву.

2018-11-03 07:24 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsAdapter.kt
> +//        setItems(news)
Не оставляй закомментированный код =)

2018-11-03 07:24 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        getNews()
Слушай, почитал немного статей про `ViewModel` и ее более-менее правильное использование в рамках MV*-архитектур, подсмотрел следующее:

По-хорошему, `View` (в роли которой здесь выступает твоя Activity) не должна самостоятельно дергать сама дергать какой-то запрос. Во View ты всего лишь должен подписаться на обновления LiveData.

```
class MyActivity {

    private val viewModel: MyViewModel

    override fun onCreate(savedInstanceeState: Bundle?) {
        super.onCreate(savedInstanceState)
        viewModel.newsList.observe(this, Observer {
            // обновление адаптера
        }
    }

    override fun onStop() {
        super.onStop()
        viewModel.removeObservers(this)
    }

}
```

Сам запрос ты помещаешь внутрь ViewModel.

```
class MyViewModel: ViewModel() {

    val news = MutableLiveData<List<DisplayableItem>>

    private val compositeDisposable = CompositeDisposable()

    init {
        Single.fromCallable {
            DataUtils.getNews()
        }
        .delay(5L, TimeUnit.SECONDS)
        .map { ... }
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe({
             // обновить LiveData --> сигнал пойдет во вью, обновится адаптер
        }, { error -> 

         })
         .bind() // добавляет в CompositeDisposable
    }
     
}
```

И вот это - вполне уже адекватная модель работы, как мне кажется. Потому что реально то, что написано выше смотрится как такой здоровенный костыль.

Давай переделаем.

Почитать можно вот тут: 
https://proandroiddev.com/mvp-to-mvvm-transformation-611959d5e0ca

2018-11-03 07:24 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        getNews()
А еще - в `ViewModel` есть метод `onCleared` - его можно юзать для очищения compositeDisposable

2018-11-03 07:24 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +    override fun initUx() {
Но, честно говоря, обычно в Activity или Fragment не так много различных вьюшек и листенеров, чтобы их разносить по разным методам. 
Но тут пока действуют твои правила =) Придешь в какую-нибудь команду, там уже будут, возможно, другие правила =) Помни об этом =)

2018-11-07 04:54 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +        private const val DELAY: Long = 2
done

2018-11-07 04:56 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsApp.kt
> +    @SuppressLint("LongLogTag")
Там где Log.w, такая ошибка: "The logging tag can be at most 23 characters, was 32 (Undeliverable exception received)"

2018-11-07 04:57 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/MainActivity.kt
> +                    Log.e(this.javaClass.simpleName, it.message)
завел

2018-11-07 04:57 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/adapters/NewsAdapter.kt
> +//        setItems(news)
убрал

2018-11-10 07:38 UTC, PStrelchenko approved these changes

2018-11-10 18:22 UTC, merged