Exercise 5 network
dmersiyanov/AndroidAcademy pull request #5
Opened 2018-11-11 18:52 UTC by dmersiyanov

2018-11-17 20:07 UTC, PStrelchenko requested changes
Чуток изменений нужно

2018-11-17 20:07 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
Эм, а почему версии ретрофита и его конвертеров отличаются? =/

2018-11-17 20:07 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/about/AboutActivity.kt
> +@Layout(R.layout.activity_about)
Ой, ну ты модный =)))

2018-11-17 20:07 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +//        if (item is NewsItem) {
Мертвый код >_<

2018-11-17 20:07 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +    private fun getUrlFromIntent() {
Можно сделать прям в Kotlin-way:

```
val url by lazy {
    intent?.extras?.getString(ARGS_URL) ?: ""
}
```

2018-11-17 20:07 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +        private const val URL = "url"
Добавь к этим константам префикс `ARGS` - поможет тебе самому понимать, что это у тебя аргументы из intent-а.

2018-11-17 20:07 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsViewModel.kt
> +                    showProgress.value = true
Можно заменить на `showProgress.postValue(true)`

2018-11-17 20:07 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsViewModel.kt
> +        return context.resources.getStringArray(R.array.news_categories)[position].toLowerCase().trim()
Обычно стараются сделать так, чтобы в `presenter`-е было поменьше вещей, связанных с Android SDK, чтобы было тестировать попроще. 
Для того, чтобы отсюда убрать зависимость от context-а, можно создать специальный утилитный класс `ResourcesSource`, который будет оборачивать Context, и будет предоставлять тебе функционал для получения каких-то ресурсов - строчек, массивов, и тп.

2018-11-17 20:07 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/dto/MultimediaItemDTO.kt
> +	@field:SerializedName("copyright")
`@field:` здесь необязателен =) Можно просто оставить `@SerializedName`

2018-11-17 20:07 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/mapper/NewsItemMapper.kt
> +    fun mapToNewsItems(newsItemDTOS: List<NewsItemDTO?>): List<DisplayableItem> {
Ничего не перепутал? Тут точно `List<NewsItemDTO?>`, а не `List<NewsItemDTO>?` 

?

2018-11-17 20:07 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/network/RestAPI.kt
> +    private const val TIMEOUT_IN_SECONDS: Long = 2
`private const val TIMEOUT_IN_SECONDS = 2L`

2018-11-17 20:07 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/network/RestAPI.kt
> +    fun getNews(category: String): Single<NewsResponseDTO> {
Перенеси выше приватных функций. Не забываем про код-стайл

2018-11-17 20:07 UTC, PStrelchenkoHH commented on app/src/main/res/menu/menu_list.xml
> +    <!--<item-->
Мертвечинкой пахнет

2018-11-17 20:35 UTC, dmersiyanov commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
а потому что он их не подсвечивает почему-то :) исправил

2018-11-17 20:35 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/about/AboutActivity.kt
> +@Layout(R.layout.activity_about)
ахаха)

2018-11-17 20:37 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +//        if (item is NewsItem) {
убрал

2018-11-17 20:39 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +    private fun getUrlFromIntent() {
добавил, но мне так не очень нравится т.к если там будут еще аргументы, то я бы вынес их все в метод чтобы было понятно откуда они берутся

2018-11-17 20:40 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +        private const val URL = "url"
добавил

2018-11-17 20:47 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/dto/MultimediaItemDTO.kt
> +	@field:SerializedName("copyright")
а это я через плагин делал, удалять лень)

2018-11-17 20:49 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/mapper/NewsItemMapper.kt
> +    fun mapToNewsItems(newsItemDTOS: List<NewsItemDTO?>): List<DisplayableItem> {
Это я случайно создал, до того как увидел что нужно просто веб-вью сделать и оставил на случай если понадобится в след домашке.

Тут типа с расчетом на очень плохой бек-энд, когда у тебя сам лист может быть null и объект в листе тоже может быть null.

Это тестовый вариант в общем, если не пригодится дальше то удалю)

2018-11-17 20:50 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/network/RestAPI.kt
> +    private const val TIMEOUT_IN_SECONDS: Long = 2
поправил

2018-11-17 20:50 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/network/RestAPI.kt
> +    fun getNews(category: String): Single<NewsResponseDTO> {
точно)

2018-11-17 20:51 UTC, dmersiyanov commented on app/src/main/res/menu/menu_list.xml
> +    <!--<item-->
ах, это я забыл)

2018-11-18 11:36 UTC, PStrelchenko approved these changes
В целом все ок, мерджи, и вперед к 6 ДЗ

2018-11-18 11:36 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +        initUi()
зачем 2 отдельных метода?.. Я про `initUi` и `initUi(savedInstanceState)`. Почему бы не совместить в один метод с nullable аргументом? Сам не запутаешься, когда какой использовать?

2018-11-18 16:18 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +        initUi()
лол, ну да странно. Я подумал, что буду использовать с savedInstanceState когда он явно нужен. 
Попробую перенести в один.

2018-11-18 16:18 UTC, merged