Exercise 6 persistency
dmersiyanov/AndroidAcademy pull request #6
Opened 2018-11-25 11:03 UTC by dmersiyanov

2018-12-01 09:45 UTC, PStrelchenko requested changes
Реквест ченджей

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize"/>
В этой домашке такой штуки не должно уже быть =) ты же получаешь данные из БД, а не из web view.

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        var INSTANCE: AppDatabase? = null
наверное, забыл модификатор `private` - не похоже, что этот объект должен быть извне доступен

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/database/NewsDao.kt
> +//    @Query("SELECT * FROM NewsEntity")
Dead code >_<

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/database/NewsDao.kt
> +    @Query("SELECT * FROM NewsEntity")
Маленькое замечание - обычно названия таблиц пишут в `snake_case`. Но это так, кодстайл.

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/database/NewsDaoAsync.kt
> +    @Query("SELECT * FROM NewsEntity")
Не очень понял логику разделения методов DAO, относящихся к одной и той же сущности. В чем прикол?

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        fun getAppDataBase(context: Context): AppDatabase? {
Я бы сделал `: AppDatabase` - у тебя все равно приложение будет работать неправильно, если база данных будет null. 

Придется тогда сделать `return INSTANCE!!`

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        fun destroyDataBase(){
А где и зачем дестроишь?

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +        if (title.isNotBlank()) {
`supportActionBar?.title = title.takeIf { it.isNotBlank() } ?: ""`

Тру котлин вэй =)

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +        fun display(context: Context, itemId: Int?) {
А есть смысл передавать nullable сюда? Насколько я понимаю логику приложения, если ты пытаешься показать новость с id = null --> ты не можешь ничего показать толком =)

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsRepo.kt
> +    private val newsDao: NewsDao?
А почему бы передавать эти DAO прям в конструктор? Тогда и контекст здесь будет не нужен.

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsRepo.kt
> +    fun clear(): Completable = Completable.fromAction {
В чем разница с `fromCallable`?

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsViewModel.kt
> +                    when (it.isNotEmpty()) {
Выражение `when` в Kotlin не очень смотрится, когда у тебя всего 2 ветки кода. Можно написать через `if` - будет даже понятнее.

```
if (it.isNotEmpty()) {
    news.postValue(it)
} else {
    getNews(DEFAULT_CATEGORY, false)
}
```

На одну строчку кода больше. правда.

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsViewModel.kt
> +                        else -> getNews(DEFAULT_CATEGORY, false)
Немного странно, что `DEFAULT_CATEGORY` - это число, а не enum-значение.
З.Ы. а зачем тебе array.xml, если у тебя уже есть enum с этими же самыми значениями?

2018-12-01 09:45 UTC, PStrelchenko commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/NewsEntity.kt
> +        val newsCategory: String,
А если написать `TypeConverter` для enum значения - можно будет написать `val category: Category`

2018-12-01 09:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/features/onboarding/OnBoardingRepo.kt
> +        writer.putInt(LAUNCH_COUNTER, counter + 1).commit()
Почему не `apply`? тебе важно здесь именно синхронное сохранение?

2018-12-01 09:45 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_news_details.xml
> +            xmlns:tools="http://schemas.android.com/tools"
Здесь не нужны 
```
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools"
```

Их можно указать 1 раз в родительском тэге всей верстки

2018-12-01 09:45 UTC, PStrelchenkoHH commented on app/src/main/res/layout/layout_image_text_view.xml
> +        android:contentDescription="TODO" tools:srcCompat="@drawable/finch_logo" />
`@null`, если не хочешь ничего писать, или `tools:ignore="ContentDescription"`

2018-12-01 09:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/mapper/NewsItemMapper.kt
> +    fun fromDatabase(newsEntities: List<NewsEntity?>): List<NewsItem> {
Уверен, что здесь `newsEntities: List<NewsEntity?>`, а не `newsEntities: List<NewsEntity>?`?
Очень странно выглядит постоянное использование `it?`.

2018-12-01 09:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/mapper/NewsItemMapper.kt
> +    fun toDatabase(newsResponseDTO: NewsResponseDTO?, context: Context): List<NewsEntity>? {
`Context` в converter-е в базу данных? Кажется, что что-то не так =) 
Почему нельзя в Long сконвертировать? String - это же только для UI.

2018-12-08 13:14 UTC, dmersiyanov commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize"/>
Убрал

2018-12-08 13:14 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        var INSTANCE: AppDatabase? = null
верно

2018-12-08 13:15 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/NewsDao.kt
> +//    @Query("SELECT * FROM NewsEntity")
убрал

2018-12-08 13:16 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/NewsDao.kt
> +    @Query("SELECT * FROM NewsEntity")
поменял DB_NAME на "news_db"

2018-12-08 13:17 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/NewsDaoAsync.kt
> +    @Query("SELECT * FROM NewsEntity")
Я сделал по примеру как у Саши Блинова. Как минимум потому что я не могу два метода getAll() засунуть в один Dao. 
Как быть?

2018-12-08 13:24 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/onboarding/OnBoardingRepo.kt
> +        writer.putInt(LAUNCH_COUNTER, counter + 1).commit()
заменил

2018-12-08 13:25 UTC, dmersiyanov commented on app/src/main/res/layout/activity_news_details.xml
> +            xmlns:tools="http://schemas.android.com/tools"
убрал

2018-12-08 13:26 UTC, dmersiyanov commented on app/src/main/res/layout/layout_image_text_view.xml
> +        android:contentDescription="TODO" tools:srcCompat="@drawable/finch_logo" />
тут забыл

2018-12-08 13:38 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/mapper/NewsItemMapper.kt
> +    fun fromDatabase(newsEntities: List<NewsEntity?>): List<NewsItem> {
Я не знаю как правильно делать. Переписал из расчета что и список и айтем может быть null. Насколько это правильно?

2018-12-08 13:43 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/mapper/NewsItemMapper.kt
> +    fun toDatabase(newsResponseDTO: NewsResponseDTO?, context: Context): List<NewsEntity>? {
Просто я юзаю NewsEntity в UI из-за нежелания мапить туда-сюда. А fromDatabase() написал на всякий случай)

2018-12-08 13:46 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        fun getAppDataBase(context: Context): AppDatabase? {
исправил

2018-12-08 13:47 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        fun destroyDataBase(){
Нигде, сделал по примеру от Блинова

2018-12-08 13:48 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +        if (title.isNotBlank()) {
Исправил

2018-12-08 13:50 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsDetail/NewsDetailsActivity.kt
> +        fun display(context: Context, itemId: Int?) {
логично) исправил

2018-12-08 14:15 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsRepo.kt
> +    private val newsDao: NewsDao?
да, хорошее решение - поправил

2018-12-08 14:28 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsRepo.kt
> +    fun clear(): Completable = Completable.fromAction {
Вот что по доке. Но я не очень понимаю разницу для меня.

fromCallable - Returns a Completable which when subscribed, executes the callable function, ignores its normal result and emits onError or onComplete only.

fromAction - Returns a Completable instance that runs the given Action for each subscriber and emits either an unchecked exception or simply completes.

2018-12-08 14:30 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsViewModel.kt
> +                    when (it.isNotEmpty()) {
поправил

2018-12-08 14:32 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsViewModel.kt
> +                        else -> getNews(DEFAULT_CATEGORY, false)
Я хотел прикрутить enum к DTO модели, но оказалось не очень удобно.

2018-12-08 14:33 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/NewsEntity.kt
> +        val newsCategory: String,
Пока не дошли руки до него

2018-12-09 08:57 UTC, PStrelchenko requested changes
Зацепился взгляд за некоторые вещи

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/NewsApp.kt
> +        lateinit var context: Context
Я бы сделал это поле приватным и добавил геттер, потому что, ну знаете, публичные может кто-то поменять =)

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +    open fun showProgress(show: Boolean) = progress?.visible(show)
Ну, такое себе решение. Забудет какой-нить разработчик переопределить этот метод в активити, где нет никаких `<include layout="@layout/view_progress" />` и бумс.

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        private var INSTANCE: AppDatabase? = null
а зачем с большой буквы? Это ж не константа.

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +                    INSTANCE = Room.databaseBuilder(context.applicationContext, AppDatabase::class.java, DB_NAME).build()
Даешь double lock! Тут тоже надо проверять на `null`. 
В смысле, что раз уж начал делать "безопасный синхронный метод создания синглетона" - юзай максимально безопасный вариант =) 

if (a == null) {
    synchronized(AClass::class) {
        if (a == null) {
            // create instance
        }
    }
     return a;
}

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        fun getNewsDao(context: Context): NewsDao {
Зачем нужны эти методы?.. Абстрактные методы наверху и так тебе создадут нужные инстансы

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/database/NewsDao.kt
> +    @Query("SELECT * FROM NewsEntity")
Я вообще говорил про `NewsEntity`. Типо обычно пишут `news_entity`.
А название базы данных можно было и оставить. 

З.Ы. Обычно у имени БД еще и расширение `.db` ставят

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/database/NewsDaoAsync.kt
> +    @Query("SELECT * FROM NewsEntity")
Уже писал по этому вопросу -- назвать методы по-разному же можно.
```
getAll(): List<>
getAllObservable(): Observable<List<>>
```

Я уверен, что Саша это сделал исключительно ради примера и наглядности =)

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/database/converter/DateConverter.kt
> +    fun dateToTimestamp(date: Date?): Long? {
Мне кажется, я задавал этот вопрос, но повторю: а обратно не надо писать конвертер? Чтоб из Long получать Date?

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/features/newsList/NewsRepo.kt
> +    fun clear(): Completable = Completable.fromAction {
Обсудили

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/features/newsList/model/mapper/NewsItemMapper.kt
> +    fun toDatabase(newsResponseDTO: NewsResponseDTO?, context: Context): List<NewsEntity>? {
обсудили

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/features/onboarding/OnBoardingViewModel.kt
> +                    .delay(DELAY_IN_SECONDS, TimeUnit.SECONDS)
а тут observeOn(AnroidSchedulers.mainThread()) не нужен? Делей же на computation потоке выполняется

2018-12-09 08:57 UTC, PStrelchenkoHH commented on app/src/main/java/com/dmity/androidacademy/utils/DateTimeUtils.kt
> +        return if (date == null) ""
Кажется, это лучше переписать в 

```
return when {
    date == null -> ""
    DateUtils.isToday(date.time) -> {

    }
    else -> {

    }
}
```

2018-12-09 12:24 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/NewsApp.kt
> +        lateinit var context: Context
добавил private set

2018-12-09 12:27 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/base/BaseActivity.kt
> +    open fun showProgress(show: Boolean) = progress?.visible(show)
Согласен, буду иметь ввиду, но пока вроде выглядит неплохо :)

2018-12-09 12:28 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        private var INSTANCE: AppDatabase? = null
переименовал

2018-12-09 12:37 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +                    INSTANCE = Room.databaseBuilder(context.applicationContext, AppDatabase::class.java, DB_NAME).build()
сделал

2018-12-09 12:40 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/AppDatabase.kt
> +        fun getNewsDao(context: Context): NewsDao {
Верно, я почему-то подумал что так будет удобнее - исправил

2018-12-09 12:46 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/database/converter/DateConverter.kt
> +    fun dateToTimestamp(date: Date?): Long? {
Он у меня не заработал, я гуглил этот момент, но так и не смог нормально конвертить. Поэтому кстати сделал маппинг даты в стрингу при сохранении в базу.

В общем я просто убираю этот конвертер)

2018-12-09 12:48 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/features/onboarding/OnBoardingViewModel.kt
> +                    .delay(DELAY_IN_SECONDS, TimeUnit.SECONDS)
Добавил, но не понял чем это нам грозит)

2018-12-09 12:59 UTC, dmersiyanov commented on app/src/main/java/com/dmity/androidacademy/utils/DateTimeUtils.kt
> +        return if (date == null) ""
Согласен, получилось поинтереснее

2018-12-09 13:14 UTC, PStrelchenko approved these changes
гут!

2018-12-09 13:41 UTC, merged